openapi: 3.0.3
info:
  title: Eliminator Domain
  description: >-
    Eliminator domain specification. Used to save sub-merchants in Eliminator DB.
  contact:
    email: productintegration@ethoca.com
  license:
    name: Copyright (c) 2021 Ethoca Limited. All Rights Reserved.
    url: "https://www.ethoca.com/terms-of-use"
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
    description: localhost endpoint
tags:
  - name: Eliminator Domain
    description: Eliminator Domain
paths:
  /api/cms-submerchants:
    post:
      tags:
        - Eliminator Domain
      summary: Clarity Merchant Service sub-merchant endpoint
      description: Clarity Merchant Service endpoint used to query sub-merchant resources
      operationId: getCmsSubMerchants
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CmsSubMerchant"
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CmsResponse"
components:
  schemas:
    CmsSubMerchant:
      title: RequestBody
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          description: >-
            Sub-merchant name
          example: "Microsoft XBox"
        subMerchantId:
          type: string
          minLength: 1
          maxLength: 100
          description: >-
            Sub-merchant identification
          example: "ABC123456"
        salesForceAccountNumber:
          type: string
          minLength: 1
          maxLength: 50
          description: >-
            SalesForce account number
          example: "ABC123456"
        status:
          type: string
          description: >-
            Sub-merchant status. Either ACTIVE or INACTIVE
          example: "ACTIVE"
        merchantType:
          type: string
          minLength: 1
          maxLength: 50
          description: >-
            Entity type. Either GATEWAY, DIRECT, or SUB_MERCHANT
          example: "SUB_MERCHANT"
    CmsResponse:
      title: ResponseBody
      type: object
      properties:
        salesForceAccountNumber:
          type: string
          minLength: 1
          maxLength: 50
          description: >-
            SalesForce account number
          example: "WXYZ9876"
        subMerchantStatus:
          type: string
          minLength: 1
          maxLength: 100
          description: >-
            Sub-merchant status. Can be either ACTIVE or INACTIVE
          example: "ABC123456"
